services:
  - type: web
    name: lumilens-api
    runtime: python
    plan: free  # Specify free tier
    region: oregon  # Choose region
    branch: main  # Deploy from main branch
    buildCommand: |
      buildCommand: |
      # Use optimized requirements for faster builds (no CUDA packages)
      pip install --cache-dir /opt/render/project/.cache/pip --upgrade pip
      pip install --cache-dir /opt/render/project/.cache/pip -r requirements-render.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: HOST
        value: 0.0.0.0
      - key: CHROMA_PATH
        value: /tmp/chroma_db
      - key: DATA_PATH
        value: /tmp/data
      # Add these in Render Dashboard (sensitive values):
      # OPENAI_API_KEY - Your OpenAI API key
      # SECRET_KEY - Generate a secure random string
      # ALLOWED_ORIGINS - ["https://your-frontend-url.vercel.app","https://lumilens.ai"]
